services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src:/app/src"
      - "/app/node_modules"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_PORT: 0
