services:
  mongo:
      image: mongo:latest
      env_file:
        - "mongo.env"
      ports:
        - 27017:27017
      volumes:
        - data_mongo:/data/db

  frontend:
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    depends_on:
      - mongo
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - "./backend:/app"
    depends_on:
      - mongo
      
volumes:
  data_mongo:
