name: Deploy

on:
  push:
    branches: [ boris ]
  pull_request:
    branches: [ boris ]

  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14'
      - run: npm install
      - run: npm run build
        env:
          CI: false

      - uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./app/build
