name: Database validation

on:
  push:
    branches: [ master ]
    paths:
    - 'app/src/db/**.json'
  pull_request:
    branches: [ master ]
    paths:
    - 'app/src/db/**.json'
    
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate db json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: ./app/src/db/schema.json
          INPUT_JSONS: ./app/src/db/db.json
